### ISSUE TITLE
Schema should include appropriate error statuses in responses

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/history4feed#1]
https://github.com/muchdogesec/history4feed/blob/webserver/design/mvp/api.md#errors

This helps users handle errors in their downstream tools appropriately

Currently the schema only shows 200 responses

**Comment by fqrious** [comment]
document is gone

**Comment by himynamesdave** [comment]
@fqrious i only see the schemas for 200 responses in the spec

![image](https://github.com/user-attachments/assets/75be556f-0554-4671-902c-a13ebfb7861d)
