### ISSUE TITLE
Swagger UI schema for post feed should have include_remote_blogs default as false

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/history4feed#21]
currently

{
  "url": "string",
  "include_remote_blogs": true
}

should be

{
  "url": "string",
  "include_remote_blogs": false
}

![image](https://github.com/user-attachments/assets/747d7f7a-49e8-4833-8273-8be30eb57e28)

**Comment by fqrious** [comment]
it's false if you don't include it, however, I'm not sure I can control what swagger-ui shows to you
