### ISSUE TITLE
Issue with identification of some URLs

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/history4feed#25]
https://muchdogesec.github.io/fakeblog123/feed.xml

This is a valid atom feed, but seems to stick as running forever, with 0 feeds downloaded...

```
{
  "id": "82d56ea2-bbfa-47ce-a0c8-3da529b4fc0d",
  "created": "2024-08-14T10:22:02.304532Z",
  "state": "retrieving",
  "history4feed_status": "running",
  "item_count": 0,
  "processed_items": 0,
  "failed_processes": 0,
  "feed": "a111dc79-5cd3-5754-87fe-69d90f96abf9"
}
```

**Comment by fqrious** [comment]
I fixed an issue causing no feed to be retrieved (the link in the atom is relative and we expect absolute), but I can't reproduce the "running" forever
