### ISSUE TITLE
add new PATCH post endpoint

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/history4feed#27]
We currently have the endpoint

```
PATCH /api/v1/feeds/{feed_id}/
```

This goes away and looks for updates in the feed since the last run time.

However, there are some problems with this. Lets say an author updates a post from 2020. Sometimes this update does not mean that post will be pushed to the top of the RSS feed (some only use created time to show posts and not modified time), and thus these updates will never be captured in this update request.

We should therefore add a PATCH post endpoint

```
PATCH /api/v1/feeds/{feed_id}/posts/{post_id}/
```

This will then go the the URL of the post, and reindex the data if a 200 response returned.

If the post hits a non 200 response, then it will not change the data and show an error to the user.

**Comment by himynamesdave** [comment]
@fqrious the first post indexes fine.

I then update blog post at source and run update request. The description property then shows as empty (was correctly populated before)

```
{
  "page_size": 50,
  "page_number": 1,
  "page_results_count": 4,
  "total_results_count": 4,
  "posts": [
    {
      "id": "74603014-197a-459f-9e72-84dd13e558f6",
      "datetime_added": "2024-08-29T14:08:47.300021Z",
      "datetime_updated": "2024-08-29T14:13:29.862646Z",
      "title": "Update this post for testing updates to posts",
      "description": "<html><body></body></html>",
      "link": "https://muchdogesec.github.io/fakeblog123///test3/2024/08/20/update-post.html",
      "pubdate": "2024-08-20T10:00:00Z",
      "author": "David G",
      "is_full_text": true,
      "content_type": "text/html; charset=utf-8",
      "categories": [
        "blog",
        "test"
      ]
    },
```

it seems the update page content is not indexed correctly

Here is the post https://muchdogesec.github.io/fakeblog123///test3/2024/08/20/update-post.html

**Comment by fqrious** [comment]
![Image](https://github.com/user-attachments/assets/a180ead2-c918-4306-b95a-dd845882ca14)

that's just how html-article works, the page doesn't contain anything

**Comment by himynamesdave** [comment]
hmm that's odd, because it works on the original article. maybe it's the content. let me try some more tests

**Comment by himynamesdave** [comment]
@fqrious posts are not updating

See my update to the blog

https://github.com/muchdogesec/fakeblog123/commits/main/

The only property that has changes in the h4f response is the `datetime_updated` despite me running patch each update

```
{
  "id": "8f16d2be-7b06-5f3c-a851-9cce31b4fec8",
  "datetime_added": "2024-09-02T05:34:56.774798Z",
  "datetime_updated": "2024-09-02T05:46:44.403941Z",
  "title": "Update this post for testing updates to posts",
  "description": "<html><body><div><div class=\"post-content e-content\" itemprop=\"articleBody\">\n    <p>This is just a normal post with an ip address 1.1.1.1</p>\n\n<p>And a domain google.com</p>\n\n<p>You need to add quite a lot of text for it to be picked up as an article by readability https://pypi.org/project/readability/</p>\n\n<p>Add more content to it over time to see how updates happen in the feed.</p>\n\n<p>And here’s a bit more content in the article just to make sure.</p>\n\n<p>Hope you enjoy it. Add your content below.</p>\n\n  </div></div></body></html>",
  "link": "https://muchdogesec.github.io/fakeblog123///test3/2024/08/20/update-to-post-1.html",
  "pubdate": "2024-08-20T10:00:00Z",
  "author": "David G",
  "is_full_text": true,
  "content_type": "text/html; charset=utf-8",
  "categories": [
    "blog",
    "test"
  ]
}
```

Please do use fakeblog 123 to test

**Comment by himynamesdave** [comment]
Since last commit, now no posts are being indexed -- count remains at 0


```
{
  "page_size": 50,
  "page_number": 1,
  "page_results_count": 1,
  "total_results_count": 1,
  "feeds": [
    {
      "id": "d1d96b71-c687-50db-9d2b-d0092d1d163a",
      "count_of_posts": 0,
      "title": "Your awesome title",
      "description": "RSS -- Contains encoded html -- FULL CONTENT",
      "url": "https://muchdogesec.github.io/fakeblog123/feeds/rss-feed-encoded.xml",
      "earliest_item_pubdate": null,
      "latest_item_pubdate": null,
      "datetime_added": "2024-09-03T05:13:03.126167Z",
      "feed_type": "rss",
      "include_remote_blogs": false
    }
  ]
}

```
