### ISSUE TITLE
Generate post ID using UUIDv5

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/history4feed#28]
Namespace (same as used to generate Feed ID)

The values should be:

`<POST URL>+<PUB_DATE>`

**Comment by himynamesdave** [comment]
Just realised we will also need to include feed ID in this @fqrious (I built some tests and realised they all point to the same URL, which is possible IRL: https://github.com/muchdogesec/history4feed/blob/main/tests/add_fakeblog123_feeds.py)

so e.g. for (https://muchdogesec.github.io/fakeblog123/feeds/rss-feed-encoded.xml)

6c6e6448-04d4-42a3-9214-4f0f7d02694e

d1d96b71-c687-50db-9d2b-d0092d1d163a+https://muchdogesec.github.io/fakeblog123///test3/2024/08/07/testing-extractions-1.html+2024-08-07T08:00:00Z

=

98f255ca-e791-5aef-93c8-eaf03bebaf43

**Comment by himynamesdave** [comment]
@fqrious can you show me how UUID generation is happening please?

d1d96b71-c687-50db-9d2b-d0092d1d163a+https://muchdogesec.github.io/fakeblog123///test3/2024/08/20/update-post.html+2024-08-20T10:00:00Z = 22173843-f008-5afa-a8fb-7fc7a4e3bfda

```

{
  "page_size": 50,
  "page_number": 1,
  "page_results_count": 4,
  "total_results_count": 4,
  "posts": [
    {
      "id": "166974b3-9fb3-54f9-a101-0fae6e80da22",
      "datetime_added": "2024-09-02T05:21:45.153164Z",
      "datetime_updated": "2024-09-02T05:21:46.712705Z",
      "title": "Update this post for testing updates to posts",
      "description": "<html><body></body></html>",
      "link": "https://muchdogesec.github.io/fakeblog123///test3/2024/08/20/update-post.html",
      "pubdate": "2024-08-20T10:00:00Z",
      "author": "David G",
      "is_full_text": true,
      "content_type": "text/html; charset=utf-8",
      "categories": [
        "blog",
        "test"
      ]
```

I suspect the time is passed differently to what i'm entering

**Comment by fqrious** [comment]
the uuid generation includes microseconds


![Image](https://github.com/user-attachments/assets/97b4d015-6ba1-4fba-9e4b-703b44589ef1)
