### ISSUE TITLE
Add ability to manually backfill post in a feed

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/history4feed#47]
In some cases a wayback machine archive does not exist, so only the latest posts are indexed.

e.g.

https://www.crowdstrike.com/en-us/blog/feed

https://www.crowdstrike.com/en-us/blog

To solve this problem, it should be possible to add posts in a feed manually using the endpoint. User can supply the details of each post, and crucially a URL that will be crawled.

```
POST /api/v1/feeds/{feed_id}/posts/
```

The `id`, `datetime_added`, and `datetime_updated` properties  of the post will be generated in the normal way. 

A user should be able to pass the following in the body of the request;

```
    {
      "profile_id": "OPTIONAL",
      "title": "REQUIRED - MAX 256 chars",
      "link": "REQUIRED - URL",
      "pubdate": "REQUIRED",
      "author": "OPTIONAL - MAX 256 chars",
      "categories": [
        "OPTIONAL - LIST:
      ]
    },
```

The `description` is added to the post object in the normal way by navigating to the `link` provided by the user.

The `is_full_text` and `content_type` are also autogenerated.

We should validate that `url` does not already exist for the feed. If it does, return an error (also normalise urls entered by user with trailing fileextension e.g. david.com/blog/post is same as david.com/blog/post.html

**Comment by fqrious** [comment]
> also normalise urls entered by user with trailing fileextension e.g. david.com/blog/post is same as david.com/blog/post.html
This is wrong and will cause problems in the future
