### ISSUE TITLE
Add `id` fitler to GET Feeds (JSON) endpoint

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/history4feed#5]
Allow user to pass one or more feed ids to filter the response.

**Comment by fqrious** [comment]
do you mean `/api/v1/feeds/{feed_id}/posts/` or `/api/v1/feeds/`?

**Comment by himynamesdave** [comment]
`/api/v1/feeds/` is correct

Not needed for `/api/v1/feeds/{feed_id}/posts/ ` as feed id already in path

**Comment by fqrious** [comment]
but `/api/v1/feeds/{feed_id}/` already exists
