### ISSUE TITLE
Change UUID logic for feed / post generation

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/history4feed#58]
See commit

https://github.com/muchdogesec/history4feed/commit/42fc36e80cead3e2476d1de63d16c2756afd03d5

In Obstracts web, it is likely we will need to add the same blog with multiple profiles (e.g. to allow specific users access to one profile, other to another -- e.g. paid users to an AI profile, free users to a standard profile)

To support this, we should update UUID generation

The `id` of a Feed is generated using a UUID v5. The namespace used is `6c6e6448-04d4-42a3-9214-4f0f7d02694e` and the value used is `<FEED_URL>+<PROFILE_ID>`. Therefore, you cannot add a Feed URL/Profile combination that already exists.

 Each post ID is also generated using a UUID v5. The namespace used is `6c6e6448-04d4-42a3-9214-4f0f7d02694e` and the value used is `<FEED_ID>+<POST_URL>+<PROFILE_ID>`
 
 Note for posts, the profile id matches the profile id user when then blog was added, unless it is passed in the PATCH or backfill post endpoint, where the profile ID passed will be used to generate the IDs

**Comment by fqrious** [comment]
But `feed` no longer depend on profile, this only makes sense if feed depends on profile

**Comment by himynamesdave** [comment]
Sure, but you need to pass profile id (optionally) in this request (as you can with all POST/PATCH requests) so it is available to use.

The main point of doing this is for Obstracts web / Obstracts core (which will always require profile), however, it seems best to add it to h4f at the core level?

**Comment by fqrious** [comment]
This has so many problems. Does patching a post change the `id` of the post?

**Comment by himynamesdave** [comment]
@fqrious ok, then lets keep it as is. I'll mark as won't do for now and find a workaround in Obstracts web
