### ISSUE TITLE
Wayback machine hack still ongoing, need to handle gracefully

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/history4feed#60]
https://mashable.com/article/internet-archive-down-again?test_uuid=01iI2GpryXngy77uIpA3Y4B&test_variant=b

As such there service keeps going down. Hopefully the stability will return soon

Obstracts currently retries forever when WBM is down

```
celery-1  | [2024-10-23 17:26:43,199: INFO/ForkPoolWorker-8] Fetching `http://web.archive.org/cdx/search/cdx?from=20200101&to=20241023&url=https%3A%2F%2Fmuchdogesec.github.io%2Ffakeblog123%2Ffeeds%2Frss-feed-encoded.xml&filter=statuscode%3A200&output=json&collapse=digest` via scrapfile.io
celery-1  | [2024-10-23 17:26:45,580: WARNING/ForkPoolWorker-8] PROXY_GET Request failed for `http://web.archive.org/cdx/search/cdx?from=20200101&to=20241023&url=https%3A%2F%2Fmuchdogesec.github.io%2Ffakeblog123%2Ffeeds%2Frss-feed-encoded.xml&filter=statuscode%3A200&output=json&collapse=digest`, status: 503, reason: DONE
```

If we get a 503 > 10 times, the app should stop retrying and default to the live feed entered by user

We should also track this in the job (perhaps in the `info` property "WBM returned to many 503s"

**Comment by fqrious** [comment]
But we're not even retrying up to 10 times

**Comment by himynamesdave** [comment]
@fqrious so what is the logic now. Obstracts runs forever (using scrapfly)

**Comment by fqrious** [comment]
I already removed that, your h4f isn't up to date
