### ISSUE TITLE
Add new POST feed mode

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/history4feed#76]
It has become clear there is a big use case to cover blogs without RSS feeds.

We should allow users to add a blog in "skeleton mode", whereby they don't include an RSS/ATOM URL when creating the blog. The intention being they add the posts to that blog manually later on.

we should split the endpoints into 

```
POST /api/v1/feeds/valid_feed
POST /api/v1/feeds/invalid_feed
```

## Update current feed endpoint

`POST /api/v1/feeds/` -> `POST /api/v1/feeds/valid_feed`

Change the endpoint name, but all other logic remains the same (e.g. RSS/ATOM validation)

We also add the following optional properties

* `pretty_url` (always optional) -- there is a cosmetic URL. It is designed to show the actual blog link to browse to in a web browser (not the feed)
* `title` (optional) -- if not passed, will inherit this from the feed
* `description` (optional) -- if not passed, will inherit this from the feed

## Add invalid feed endpoint

This essentially allows user to create a skeleton feed where an RSS feed does not exist for a feed

```
POST /api/v1/feeds/invalid_feed
```

Accepts URL paramater

* `pretty_url` (always optional) -- there is a cosmetic URL. It is designed to show the actual blog link to browse to in a web browser (not the feed)
* `title` (required)
* `description` (required)

Note, this will create a feed of type `skeleton`

IMPORTANT: we should allow user the option to update (PATCH /api/v1/feeds/{feed_id}/) a feed of skeleton type, but we just allow user to update it to support name/description changes (https://github.com/muchdogesec/history4feed/issues/78)

**Comment by himynamesdave** [comment]
We decided to have one endpoint for this

Currently accepts type;

```
{
  "profile_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "include_remote_blogs": false,
  "pretty_url": "string",
  "title": "string",
  "description": "string",
  "url": "string"
}
```

However, we should validate URLs for ATOM / RSS if not skeleton mode. 

We should allow user to pass `feed_type` in body as `skeleton`. Doing this should skip the RSS / ATOM validation of `url` . If not passed, assumption is it is type RSS/ATOM

**Comment by himynamesdave** [comment]
ignore the above (just saw the skeleton endpoint :)

**Comment by himynamesdave** [comment]
@fqrious try 

```
python3 tests/test_01_add_fakeblog123_atom_rss_feeds.py \
	--feed-url https://muchdogesec.github.io/fakeblog123/feeds/atom-feed-decoded.xml
```

not how the new properties set (title/desc/pretty url) are not being stored against the feed

```
    {
      "id": "cb0ba709-b841-521a-a3f2-5e1429f4d366",
      "count_of_posts": 6,
      "pretty_url": null,
      "title": "Your awesome title",
      "description": "ATOM -- Contains decoded html (without CDATA tags, but it XML escaped) -- FULL CONTENT",
      "url": "https://muchdogesec.github.io/fakeblog123/feeds/atom-feed-decoded.xml",
      "earliest_item_pubdate": "2024-08-01T08:00:00Z",
      "latest_item_pubdate": "2024-09-01T08:00:00Z",
      "datetime_added": "2024-11-27T10:08:11.342030Z",
      "feed_type": "atom"
    },
```

**Comment by fqrious** [comment]
it got updated after the feed was retrieved.
