### ISSUE TITLE
Clean up 4xx and 5xx error schemas

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/history4feed#79]
![image](https://github.com/user-attachments/assets/05f98565-894a-4a94-9bfa-268ad7d0b0fc)

Lets implement this properly.

we should return proper errors in a json format.

**Comment by himynamesdave** [comment]
5xx errors still show html responses in the schema


![Image](https://github.com/user-attachments/assets/4ae6b42c-a517-4ebc-8f02-7a9c27bd2d44)

**Comment by fqrious** [comment]
not possible, please rebuild. I have completely removed 500 response
